on: [pull_request, push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true

      - name: Test
        uses: threeal/ctest-action@main

  macOS:
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true

      - name: Test
        uses: threeal/ctest-action@main

  Windows:
    runs-on: windows-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true

      - name: Test
        uses: threeal/ctest-action@main
