on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: 'build'
          cmakeoptions: '--config Release'
          ctestoptions: ''

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: 'build'
          cmakeoptions: '--config Release'
          ctestoptions: ''

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: HorstBaerbel/action-ctest@1.1
        with:
          sourcedir: '.'
          builddir: 'build'
          cmakeoptions: '--config Release'
          ctestoptions: ''
