on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        uses: threeal/cmake-action@v1.3.0

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        uses: threeal/cmake-action@v1.3.0

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        uses: threeal/cmake-action@v1.3.0

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
