on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        uses: threeal/cmake-action@v1.3.0

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
