on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        run: mkdir build && cd build && cmake .. && make

      - name: Test the project
        run: cd build && ctest -C Debug --output-on-failure

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        run: mkdir build && cd build && cmake .. && make

      - name: Test the project
        run: cd build && ctest -C Debug --output-on-failure

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        run: mkdir build && cd build && cmake .. && cmake --build .

      - name: Test the project
        run: cd build && ctest -C Debug --output-on-failure
