on: [pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true

      - name: Test the project
        uses: threeal/ctest-action@main

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true

      - name: Test the project
        uses: threeal/ctest-action@main

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true

      - name: Test the project
        uses: threeal/ctest-action@main
