on: [pull_request, push]

jobs:
  Linux:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build the project
        run: mkdir build && cd build && cmake .. && make

      - name: Test the project
        run: cd build && ctest -C Debug --output-on-failure

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Test
        run: |
          cd build
          ctest -C Release


  macOS:
    runs-on: macos-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Test
        run: |
          cd build
          ctest -C Release


  Windows:
    runs-on: windows-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build
