on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: HorstBaerbel/action-ctest@1.1
